[package]
name = "wasm-bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.92"
grid-engine = { path = "../grid_engine" }
serde-wasm-bindgen = "0.6.5"
js-sys = "0.3.69"
getrandom = { version = "*", features = ["js"] }