[package]
name = "grid-multiplayer"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-util = "0.3.31"
grid-engine = { path = "../grid_engine" }
tokio = { version = "1.40.0", features = ["rt", "rt-multi-thread", "macros", "sync", "io-std"] }
tokio-tungstenite = "0.24.0"
