[package]
name = "grid-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
grid = {version = "0.14.0", features = ["serde"]}
serde = {version = "1.0.203", features = ["derive"]}
serde_json = "1.0.120"
